trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.8.1'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/MultipleRanker.RankerApi.Host.csproj'
    feedsToUse: config
    nugetConfigPath: 'Nuget.Config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration Release'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/MultipleRanker.RankerApi.Contracts/MultipleRanker.RankerApi.Contracts.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
     command: 'push'
     packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
     nuGetFeedType: 'internal'
     publishVstsFeed: '5cf477e2-0565-43e7-90d9-dd224fe8394b/64a9d062-3452-4e4a-8711-69106bd6432d'
     allowPackageConflicts: true